name: CI
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Check formatting with Pretiter
      run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    needs: check-formatting
    steps:
    - uses: actions/checkout@v2
    - name: Run ESLint
      run: yarn lint